### ISSUE TITLE
Couple of things...

### ISSUE THREAD

**Issue by hmlongco** [fahimrahmanbooom/SimpleAFLoader#1]
This kinds of needs to have some service that can be injected into the environment to drive the overlay. The problem is that busy/loading spinners also need to cover the navigation bar so the user can't interrupt the process. And that means that the view that triggers the overlay isn't usually the view in which the overlay actually resides.

**Comment by fahimrahmanbooom** [comment]
Thanks, I got your point. I will try to fix the issues.
