### ISSUE TITLE
Error "Cannot find 'LoaderView' in scope"

### ISSUE THREAD

**Issue by MahinMuhammad** [fahimrahmanbooom/SimpleAFLoader#2]
LoaderView struct can not be accessed and used from my project after importing the SimpleAFLoader. From my previous package development experience I would suggest you to make the LoaderView public so that it can be accessed.

**Comment by MahinMuhammad** [comment]
I see that you have fixed that error with a fresh commit but you have to released the updated commit. Could you please add this to a new release?

**Comment by fahimrahmanbooom** [comment]
Sure. I have published a new release.
